Pickling/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from Pickling import settings
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('pickle_file.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
    ]

pickle_file/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

urlpatterns = [
    # url(r'^',views.base,name='base'),
    url(r'^$',views.base,name='base'),
    # url(r'^download/$',views.download,name='download'),
]

pickle_file/models.py
from __future__ import unicode_literals
from django.db import models

class DocumentModel(models.Model):
    docfile = models.FileField(upload_to='documents/')

pickle_file/forms.py
from django import forms
from .models import DocumentModel

class DocumentForm(forms.Form):
    docfile = forms.FileField(
        label='Select a file'
    )

pickle_file/views.py
from django.shortcuts import render,redirect
from pickle_file.forms import DocumentForm
from .models import DocumentModel
from django.template import RequestContext
from django.http import HttpResponse
from wsgiref.util import FileWrapper
import pickle
import wget
# import os
# import ctypes
# import urllib.request

def base(request):
    # Handle file upload
    if request.method == 'POST':
        form = DocumentForm(request.POST, request.FILES)
        if form.is_valid():
            newdoc = DocumentModel(docfile=request.FILES['docfile'])
            newdoc.save()
            path='media/documents/'
            f = open(path + 'cordinates.txt')
            bubble_dict = {}
            for i in f.readlines():
                lines = i.split(';')
                q_no = lines[0]
                # print q_no
                bubble_dict[q_no] = eval(lines[1])
            pickle.dump(bubble_dict, open(path + 'ref_coord_a.p', 'wb'))
            # url = 'media/documents/ref_coord_a.p'
            # response = urllib.request.urlopen(url)
            # data = response.read()  # a `bytes` object
            # text = data.decode('utf-8')
            # print('Beginning file download with urllib2...')

            # print "downloading with urllib"
            # urllib.urlretrieve(url, "code.zip")


            # Redirect to the document list after POST
            return render(request,'pickle_file/base.html')
    else:
        form = DocumentForm()  # A empty, unbound form

    # Load documents for the list page
    documents = DocumentModel.objects.last()
    context_instance = RequestContext(request)

    # Render list page with the documents and the form
    return render(request,
        'pickle_file/base.html',
        {'documents': documents, 'form': form},context_instance

    )
# def download(url):
#     url = 'media/documents/ref_coord_a.p'
#     return HttpResponse (wget.download(url, '/Downloads/'))

pickle_file/templates/pickle_file/base.html
<html>
{% load static %}
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
    <title>File Pickling</title>
    <link rel="stylesheet" href="{% static 'pickle_file/css/style.css'%}">

</head>
<body style="background-color:#868e96">
    <div class="container" style='margin-top:50px'>

    <form method="post" enctype="multipart/form-data">{% csrf_token %}
     <p>
        <input id="id_docfile" type="file"  class="uploading" name="docfile">
     </p>
      <input type="submit" class="submit btn btn-primary" value="Upload" />

      <a href="media/documents/ref_coord_a.p" download><input type="button"  class="submit btn btn-primary" value=Download /></a>

    </form>

    </div>

</body>
</html>